Fix include paths. Fix build for Windows compilers.
git-svn-id: https://yborm.svn.sourceforge.net/svnroot/yborm/trunk@91 6e3d5a94-014d-4e71-8e65-48e4780539f1

diff --git a/src/yborm_gen_sql b/src/yborm_gen_sql
--- a/src/yborm_gen_sql
+++ b/src/yborm_gen_sql
@@ -5,6 +5,10 @@ if [ $# != 2 ] ; then
 fi
 XSLT_FILE="`dirname $0`/yborm_gen_sql.xsl"
 if ! [ -r "$XSLT_FILE" ] ; then
-    XSLT_FILE="@prefix@/share/yborm/yborm_gen_sql.xsl"
+    XSLT_FILE="`dirname $0`/../share/yborm/yborm_gen_sql.xsl"
+    if ! [ -r "$XSLT_FILE" ] ; then
+        echo "Can't find file yborm_gen_sql.xsl"
+        exit 1
+    fi
 fi
 xsltproc --stringparam dialect "$1" "$XSLT_FILE" "$2"
